readonlyrest:

  prompt_for_basic_auth: false

  access_control_rules:

  - name: "::KIBANA::"
    auth_key: kibana:kibana
    verbosity: error

  - name: "Admin"
    auth_key: admin:passwd
    kibana_access: admin
    kibana_index: ".kibana_useradmin"
    verbosity: error

